mod.version=3.3.3
mod.id=controlify
mod.name=Controlify
mod.description=The most advanced controller mod for Minecraft.
mod.sourcesUrl=https://github.com/isXander/Controlify
mod.issuesUrl=https://github.com/isXander/Controlify/issues

curseforge.id=835847
curseforge.slug=controlify
modrinth.id=DOUdJVEm
github.repo=isXander/Controlify
# @Controlify Ping
discord.ping=<@&1146064258652712960>
discord.image-url=https://github.com/isXander/Controlify/blob/main/src/main/resources/icon.png?raw=true
discord.color=#f7faa4

# Temporary measure until https://github.com/FabricMC/fabric-loom/pull/1568
mtk.multiloader.createDefaultRuns=false

# This build is configuration cache compatible!*
# *other than a few upstream bugs...
org.gradle.configuration-cache=true

# Increase the heap size for decompilations
org.gradle.jvmargs=-Xmx4G

# Required properties until https://github.com/neoforged/NeoGradle/pull/316
neogradle.subsystems.conventions.sourcesets.automatic-inclusion=false
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
neogradle.subsystems.conventions.configurations.enabled=false
neogradle.subsystems.conventions.jarjar.create-main-jarjar=false
