dep.minecraft=26.1
meta.minecraft-range=[26.1,26.2)

dep.neoforge=26.1.2.84

dep.fapi=0.145.4+26.1.2
meta.fapi-range=[0.144.3,)

dep.yacl=3.9.6+26.1-fabric
dep.yacl-neoforge=3.9.6+26.1-neoforge
meta.yacl-range=[,)

dep.mod-menu=18.0.0
dep.sodium=0.8.9+mc26.1.1
dep.iris=1.10.9+26.1-fabric
dep.iris-neoforge=1.10.9+26.1-neoforge
dep.svc=fabric-2.6.15+26.1.1
dep.svc-neoforge=neoforge-2.6.15+26.1.1
dep.fancy-menu=3.9.8-26.1.2-fabric
dep.fancy-menu-neoforge=3.9.8-26.1.2-neoforge

