dep.minecraft=26.2
meta.minecraft-range=[26.2,26.3)

dep.neoforge=26.2.0.28-beta

dep.fapi=0.152.1+26.2
meta.fapi-range=[0.152.1,)

dep.yacl=3.9.6+26.2-fabric
dep.yacl-neoforge=3.9.6+26.2-neoforge
meta.yacl-range=[,)

dep.mod-menu=20.0.0-beta.2
dep.sodium=0.9.1+mc26.2
dep.iris=1.11.2+26.2-fabric
dep.iris-neoforge=1.11.2+26.2-neoforge
dep.svc=fabric-2.6.18+26.2
dep.svc-neoforge=neoforge-2.6.18+26.2
dep.fancy-menu=3.9.8-26.2-fabric
dep.fancy-menu-neoforge=3.9.8-26.2-neoforge
