dep.minecraft=26.3
meta.minecraft-range=[26.3,26.4)

dep.neoforge=26.3.0.7-beta

dep.fapi=0.161.0+26.3
meta.fapi-range=[0.161.0,)

dep.yacl=3.9.7+26.3-fabric
dep.yacl-neoforge=3.9.7+26.3-neoforge
meta.yacl-range=[,)

dep.mod-menu=21.0.0-beta.1
dep.sodium=0.9.2+mc26.3
dep.iris=1.11.6+26.3-fabric
#dep.iris-neoforge=1.11.6+26.3-neoforge
dep.svc=fabric-2.6.24+26.3
dep.svc-neoforge=neoforge-2.6.24+26.3
dep.fancy-menu=3.9.13-26.3-fabric
dep.fancy-menu-neoforge=3.9.13-26.3-neoforge
