dep.minecraft=26.3-snapshot-7
meta.minecraft-range=(26.2,26.4)

#dep.neoforge=26.2.0.28-beta

dep.fapi=0.156.2+26.3
meta.fapi-range=[0.156.2,)

dep.yacl=3.9.6+26.3-fabric
dep.yacl-neoforge=3.9.6+26.2-neoforge
meta.yacl-range=[,)

dep.mod-menu=21.0.0-alpha.1
#dep.sodium=0.9.1+mc26.2
#dep.iris=1.11.2+26.2-fabric
#dep.iris-neoforge=1.11.2+26.2-neoforge
#dep.svc=fabric-2.6.21+26.3-snapshot-6
#dep.svc-neoforge=neoforge-2.6.18+26.2
#dep.fancy-menu=3.9.8-26.2-fabric
#dep.fancy-menu-neoforge=3.9.8-26.2-neoforge
