name: Publish

on:
  push:
    branches:
      - multiversion/prod

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with gradle

    steps:
      - uses: actions/checkout@v4

      - name: Get mod version
        id: version
        run: |
          echo "::set-output name=VER::$(grep '^modVersion=' gradle.properties | cut -d'=' -f2)"
      - name: Fail if version already published
        run: |
          if git rev-parse -q --verify "refs/tags/v${{ steps.version.outputs.VER }}" >/dev/null; then
            echo "✋ Version ${{ steps.version.outputs.VER }} already exists, aborting."
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - name: Build all
        run: ./gradlew build --stacktrace

      - name: Publish to Modrinth
        run: ./gradlew publishModrinth --stacktrace -Pmodrinth.token=${{ secrets.MODRINTH_TOKEN }}

      - name: Publish to CurseForge
        run: ./gradlew publishCurseForge --stacktrace -Pcurseforge.token=${{ secrets.CURSEFORGE_TOKEN }}

      - name: Publish to Maven
        run: ./gradlew publish --stacktrace
        env:
          XANDER_MAVEN_USER: ${{ secrets.XANDER_MAVEN_USER }}
          XANDER_MAVEN_PASS: ${{ secrets.XANDER_MAVEN_PASS }}

      - name: Create git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version.outputs.VER }}
          git push origin v${{ steps.version.outputs.VER }}

#  run:
#    needs: build
#    runs-on: ubuntu-latest
#    name: Run Minecraft
#
#    strategy:
#      matrix:
#        target: ${{ fromJson(needs.retrieve-targets.outputs.targets) }}
