name: Release
on: [workflow_dispatch]

permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Build mod
        run: ./gradlew build --stacktrace

      - uses: actions/attest@v4
        with:
          subject-path: versions/**/build/libs/*.jar

      - name: Publish mod
        run: ./gradlew publishModrinth publishCurseforge announceDiscord publishAllPublicationsToXanderMavenRepository --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ORG_GRADLE_PROJECT_XanderMavenUsername: ${{ secrets.XANDER_MAVEN_USER }}
          ORG_GRADLE_PROJECT_XanderMavenPassword: ${{ secrets.XANDER_MAVEN_PASS }}
